// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOYsX5YASEK-pD1vlamdRHxNG-RWVyd00',
    appId: '1:599602086146:web:34a23e0c0821c66a23021b',
    messagingSenderId: '599602086146',
    projectId: 'flutter-standard-ecom-app',
    authDomain: 'flutter-standard-ecom-app.firebaseapp.com',
    storageBucket: 'flutter-standard-ecom-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxhLPPD2yzZkZdngRAUX34vGHUZ5DyDdU',
    appId: '1:599602086146:android:d782a1a92f9ae23023021b',
    messagingSenderId: '599602086146',
    projectId: 'flutter-standard-ecom-app',
    storageBucket: 'flutter-standard-ecom-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0V29fGBpRaKv2gjdsFOs7uKiqjDly1fs',
    appId: '1:599602086146:ios:0c92abba4ff9e4d423021b',
    messagingSenderId: '599602086146',
    projectId: 'flutter-standard-ecom-app',
    storageBucket: 'flutter-standard-ecom-app.appspot.com',
    androidClientId: '599602086146-o1f1reud5qdtocu9r4q1i827paa1iq67.apps.googleusercontent.com',
    iosClientId: '599602086146-6nsb7jn8v3ev2vvpt0ogpe3pte9n2q82.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStandardEcommerceApp',
  );

}